#TODO ok http配置信息
#只要一个application.yml被加载了，所有的bean都可以使用
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30
spring:
  profiles:
    active: dev
  #TODO 数据库配置
  datasource:
    url: jdbc:mysql://192.168.159.128:3306/austin?useUnicode=true&characterEncoding=UTF-8&timeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    #mysql8以下使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

  #TODO kafka相关的信息配置
  kafka:
    bootstrap-servers: "192.168.159.128:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true  #消费者的偏移量自动提交
      auto-commit-interval: 1000  #间隔1000毫秒提交一次

  #TODO redis相关配置
  redis:
    host: "192.168.159.128"
    port: 6379
    password: austin

#TODO kafka topic配置
austin:
  topic:
    name: austinTopic
  #GrayLog ip 地址 TODO
  grayLogIp: 192.168.159.128

#监控配置 NOT A MUST
#采集路径写在了prometheus.yml中
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

# Apollo TODO 分布式配置
app:
  id: austin
apollo:
  bootstrap:
    enabled: true
    namespaces: boss.austin # 需访问Apollo管理面板创建部门和项目，我创建了“boss”部门和austin项目
  # TODO Apollo的地址，端口是eureka管理界面的端口(Apollo内使用Eureka注册中心，Apollo服务和Eureka服务的地址不一样)
  config-service: "http://192.168.159.128:7000"
#  想要动态刷新配置，还需要设置Apollo的监听器
springfox:
  documentation:
    swagger-ui:
      enabled: true

# xxl job TODO
xxl:
  job:
    admin:
      addresses: "http://127.0.0.1:8081/xxl-job-admin" # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      username: admin # 后台用户名
      password: admin # 后台密码
    executor:
      appname: austin # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip: "127.0.0.1" # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: logs/xxl-job/ # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      jobHandlerName: austinJob
    accessToken:  # 执行器通讯TOKEN [选填]：非空时启用；